#pretending we're C because otherwise ruby/rvm will initialize, even with "language: dm".
#thats still relevant, for now we will be el generico: the shitcode
#do not copy and paste the travis stuff from newer stations without thought, you will include many things we do not use.
#along with that, the shell scripts are agpl.
language: generic
dist: xenial

env:
  name="Cursory Map and Compile"
  BYOND_MAJOR="512"
  BYOND_MINOR="1466"
  WEBHOOK_URL="https://discordapp.com/api/webhooks/570845853263200276/i7AssPl_0pFp5QW1K6c9NlW_AbUDpLPNUrQdgY3zhYwWFnVc7tUSOo-xS8YwBstMS4OT"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libc6:i386 libgcc1:i386 libstdc++6:i386 -qq

install:
  - curl "http://www.byond.com/download/build/${BYOND_MAJOR}/${BYOND_MAJOR}.${BYOND_MINOR}_byond_linux.zip" -o byond.zip
  - unzip byond.zip
  - cd byond
  - sudo make install
  - cd ..

script:
  - DreamMaker GooseCode.dme
  #This is the best I can do, no step x and y until we have some form of pxmove if ever ya know?
  - (! grep 'step_[xy]' _maps/**/*.dmm)

after_success:
  - wget https://raw.githubusercontent.com/warhammer-in-a-2d-spessmen-game/SS13-Age-of-the-Spess-Imperium/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
  
after_failure:
  - wget https://raw.githubusercontent.com/warhammer-in-a-2d-spessmen-game/SS13-Age-of-the-Spess-Imperium/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL

notifications:
  email: false
